server:
  port: 80
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://database-2.cxygysoqawio.us-west-2.rds.amazonaws.com:3306/innodb
    username: admin
    password: kosatest12!!
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    groups-order: DESC
    doc-expansion: none
    tags-sorter: alpha
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  show-login-endpoint: true

cors-allow-domain:
  front-end: https://main.d1fiaeemrgw9n.amplifyapp.com
  test-end: https://0n60uii660.execute-api.ap-northeast-2.amazonaws.com
  alb-end: https://0n60uii660.execute-api.ap-northeast-2.amazonaws.com

JWKS_URL: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_oCbvOn2fS/.well-known/jwks.json
